### ISSUE TITLE
Add info

### ISSUE THREAD

**Issue by victorhck** [digitaltrails/procno#2]
Hello.
Maybe at the bottom (or somewhere else) can be added total the number of procs that are showed, uptime, hostinfo or similar...
Greetings

**Comment by digitaltrails** [comment]
> Hello. Maybe at the bottom (or somewhere else) can be added total the number of procs that are showed, uptime, hostinfo or similar... Greetings

Good idea. The status area is mostly empty, it could show some basic info when there is nothing else to show. 

The normal rectangular layout of the dot-area probably precludes writing text on that.

Perhaps the hostname should be in the window and tray/icon titles.  I would think the number of processes and load average might be good to have in the status bar. 

Thanks for the feedback, much appreciated.

**Comment by digitaltrails** [comment]
All the suggested info was efficiently available.  The status bar now holds hostname, uptime, process-count and load-average (and the info is only retrieved and updated if the main window is visible).   I also put the hostname in the window/tray title.  Checked in the python, will update the release shortly.

![image](https://user-images.githubusercontent.com/5510901/147159319-53166e38-cc72-41b4-9601-767c805af30d.png)

**Comment by victorhck** [comment]
Hey! looks great! Can I suggest a couple of things more? 
Maybe the info can be showed to be more readable. I mean, separate fields with - or similar. I was thinking that maybe also can be showed (maybe in the right part) the number of processes found when you search in the upper box. something similar to this layout (searching for example firefox processes):

`---------------------------------------------------------------------------------------------------------------
|Hostname: Tux - Uptime: 2:42 - 42 processes running - Loadavg: 1m: 0.6 / 5m: 0.7 / 15m: 0.7  42 processes found |
----------------------------------------------------------------------------------------------------------------`

(since I'm not a developer, can't provide a PR with code... I could help with translation to spanish if that is in your goals! Sorry for those extra work in this holidays!! 😉 )

**Comment by digitaltrails** [comment]
Improved status bar.  A little tight for space, so I kept the text short.  Match counts will display for 5 seconds when a pattern is entered, but revert to the default status message after 5 seconds of inactivity (not shown in the screen cap).
![image](https://user-images.githubusercontent.com/5510901/147286191-5d5fda92-ad0d-412a-9cf7-0607706e96d1.png)

**Comment by digitaltrails** [comment]
> (since I'm not a developer, can't provide a PR with code... I could help with translation to spanish if that is in your goals! Sorry for those extra work in this holidays!! wink )

I have almost no knowledge in how to internationalize the code, but there is some provision for it.  Every text string that should be translated is surrounded by a tr() function call (which is what the Qt documentation suggests).  So it could be done at some point in the future if anyone was keen.  Each of the tr("strings") would need to be given corresponding translation in an external file.  I've made no provision for right-to-left languages (but that would be interesting to do).  

Based on traffic here I'm guessing this code has less than 20 users, maybe less than 5, so I'm not sure it's worth the effort yet.

**Comment by digitaltrails** [comment]
> > (since I'm not a developer, can't provide a PR with code... I could help with translation to spanish if that is in your goals! Sorry for those extra work in this holidays!! wink )
> 
> I have almost no knowledge in how to internationalize the code, but there is some provision for it. Every text string that should be translated is surrounded by a tr() function call (which is what the Qt documentation suggests). So it could be done at some point in the future if anyone was keen. Each of the tr("strings") would need to be given corresponding translation in an external file. I've made no provision for right-to-left languages (but that would be interesting to do).
> 
> Based on traffic here I'm guessing this code has less than 20 users, maybe less than 5, so I'm not sure it's worth the effort yet.

I now have a little knowledge of what is required, it seems straight forward enough.  I would be happy to try and see what can be done.  No pressure.  Just raise a new issue some time if you decide you're keen.

**Comment by victorhck** [comment]
> Based on traffic here I'm guessing this code has less than 20 users, maybe less than 5, so I'm not sure it's worth the effort yet.

To solve that I have published an article (in spanish) in my blog!! :)

https://victorhckinthefreeworld.com/2021/12/23/procno-un-monitor-de-procesos-para-linux/

**Comment by digitaltrails** [comment]
> > Based on traffic here I'm guessing this code has less than 20 users, maybe less than 5, so I'm not sure it's worth the effort yet.
> 
> To solve that I have published an article (in spanish) in my blog!! :)
> 
> https://victorhckinthefreeworld.com/2021/12/23/procno-un-monitor-de-procesos-para-linux/

Very nice.  I can even understand some of the text from a combo of technical terms and echos of long forgotten secondary-school Latin and French. 

Thanks again for the help with the content-design of the status bar, it was quite underutilised before.  I'll close this issue.  

(As I wrote earlier, if you ever do feel like doing some translation, just open a new issue and I'll add some notes on what a translator needs to do - basically, Qt have a GUI that the translator runs.)
